### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: saves/llama3-8b-ir/lora/sft_rgrf/checkpoint-22818

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: orpo  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: generate_rule_dpo
template: llama3
cutoff_len: 2048
max_samples: 150000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b-ir/lora/sft_rgrf_orpo
logging_steps: 10
save_steps: 4000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 4000
